import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vuetify from 'vite-plugin-vuetify'
import { readdirSync, existsSync, statSync, writeFileSync } from 'node:fs'
import { resolve, join, relative } from 'node:path'
import { createHash } from 'node:crypto'

// Every sketches/<slug>/index.html becomes its own page in the build,
// so each sketch stays a self-contained app the gallery loads in an iframe.
function sketchInputs() {
  const root = resolve(__dirname, 'sketches')
  const inputs = { main: resolve(__dirname, 'index.html') }
  if (!existsSync(root)) return inputs
  for (const dir of readdirSync(root, { withFileTypes: true })) {
    if (!dir.isDirectory()) continue
    const page = resolve(root, dir.name, 'index.html')
    if (existsSync(page)) inputs[`sketch-${dir.name}`] = page
  }
  return inputs
}

// Offline PWA: emit a service worker that precaches EVERY built file (the app
// shell, every sketch page and its JS, fonts, icons, manifest) so the whole
// sketchbook — gallery, viewer, and every experiment iframed inside it — runs
// with no network at all. Scans the finished output directory in closeBundle so
// nothing is missed (multi-page HTML + copied public assets). Build only.
function offlinePwa() {
  let outDir = 'dist'
  return {
    name: 'offline-pwa',
    apply: 'build',
    configResolved(config) {
      outDir = resolve(config.root || process.cwd(), config.build.outDir || 'dist')
    },
    closeBundle() {
      const files = []
      const walk = (dir) => {
        for (const ent of readdirSync(dir, { withFileTypes: true })) {
          const full = join(dir, ent.name)
          if (ent.isDirectory()) walk(full)
          else files.push(full)
        }
      }
      if (!existsSync(outDir)) return
      walk(outDir)
      // POSIX-relative paths, excluding the service worker itself and sourcemaps
      const precache = files
        .map((f) => relative(outDir, f).split('\\').join('/'))
        .filter((p) => p !== 'sw.js' && !p.endsWith('.map'))
        .sort()
      // version busts the cache whenever any file's name or size changes
      const sig = precache.map((p) => p + ':' + statSync(join(outDir, p)).size).join('|')
      const version = createHash('sha1').update(sig).digest('hex').slice(0, 10)
      const sw = `// Auto-generated by the offline-pwa Vite plugin — do not edit.
const CACHE = 'bright-waves-${version}'
const ASSETS = ${JSON.stringify(precache)}
// Resolve each precache path against the SW's own scope so it works from any
// subpath (the build uses a relative base).
const abs = (p) => new URL(p, self.registration.scope).toString()

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE)
    // add individually so one failed asset can't abort the whole precache
    await Promise.allSettled(ASSETS.map((p) => cache.add(new Request(abs(p), { cache: 'reload' }))))
    // note: we do NOT skipWaiting here — a new version waits so it never swaps
    // caches out from under a running session; it takes over on the next load.
  })())
})

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys()
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    await self.clients.claim()
  })())
})

self.addEventListener('message', (e) => { if (e.data === 'skip-waiting') self.skipWaiting() })

self.addEventListener('fetch', (e) => {
  const req = e.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  if (url.origin !== self.location.origin) return // let cross-origin pass through
  e.respondWith((async () => {
    const cache = await caches.open(CACHE)
    const hit = await cache.match(req, { ignoreSearch: true })
    if (hit) return hit
    try {
      const res = await fetch(req)
      if (res && res.ok && res.type === 'basic') cache.put(req, res.clone())
      return res
    } catch (err) {
      // offline: fall back to the cached app shell for navigations
      if (req.mode === 'navigate') {
        const shell = await cache.match(abs('index.html'), { ignoreSearch: true })
        if (shell) return shell
      }
      throw err
    }
  })())
})
`
      writeFileSync(join(outDir, 'sw.js'), sw)
    },
  }
}

export default defineConfig({
  // Relative base so the built site works from any subpath (e.g. GitHub Pages).
  base: './',
  plugins: [vue(), vuetify({ autoImport: true }), offlinePwa()],
  build: {
    rollupOptions: {
      input: sketchInputs(),
    },
  },
})
