#!/usr/bin/env node
/**
 * Writes src/lib/mdiIcons.js: a map from every "mdi-*" name used in src/ (plus
 * Vuetify's own aliases) to its @mdi/js SVG path, so only those icons ship
 * instead of the whole icon webfont. Run after adding an icon: npm run icons
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import * as mdi from '@mdi/js'

const names = new Set()
const scan = (dir) => {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f)
    if (statSync(p).isDirectory()) scan(p)
    else if (/\.(js|vue|html|mjs)$/.test(f) && !p.endsWith('mdiIcons.js')) for (const m of readFileSync(p, 'utf8').matchAll(/\bmdi-[a-z0-9]+(?:-[a-z0-9]+)*/g)) names.add(m[0])
  }
}
scan('src')
for (const m of readFileSync('node_modules/vuetify/lib/iconsets/mdi.js', 'utf8').matchAll(/'(mdi-[a-z0-9-]+)'/g)) names.add(m[1])

// Brand icons were dropped from @mdi/js; map them to a neutral stand-in.
const STAND_IN = { 'mdi-google-photos': 'mdiImageMultiple' }
const camel = (n) => 'mdi' + n.slice(4).split('-').map((s) => s[0].toUpperCase() + s.slice(1)).join('')
const ok = [...names].sort().filter((n) => (STAND_IN[n] || camel(n)) in mdi || (console.warn('no @mdi/js export for', n), false))
const id = (n) => STAND_IN[n] || camel(n)
const out = `// Generated by scripts/gen-icons.mjs (npm run icons). Do not edit.
import {
${[...new Set(ok.map(id))].map((n) => '  ' + n + ',').join('\n')}
} from '@mdi/js'

export default {
${ok.map((n) => `  '${n}': ${id(n)},`).join('\n')}
}
`
writeFileSync('src/lib/mdiIcons.js', out)
console.log(`wrote src/lib/mdiIcons.js (${ok.length} icons)`)
